# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: fastfetch-cli.fastfetch
PackageVersion: 2.2.3
PackageLocale: en-US
Publisher: fastfetch-cli
PackageName: fastfetch
License: MIT License
ShortDescription: Like neofetch, but much faster because written in C.
ManifestType: defaultLocale
ManifestVersion: 1.5.0
